### ISSUE TITLE
TypeError using pretrained tokenizer for one label classification 

### ISSUE THREAD

**Issue by NtaylorOX** [simonlevine/clinical-longformer#5]
## Python env:

Python3.6.9

## Packages:
pandas==1.1.1
tensorboard==2.2.0
torch==1.6.0
transformers==3.1.0
pytorch-lightning==0.9.0
pytorch-nlp==0.5.0

## Issue:
When attempting to load/train with the following: python classifier_pipeline/training_onelabel.py --transformer_type roberta-long --encoder_model simonlevine/bioclinical-roberta-long

It results in the following error:
Traceback (most recent call last):
  File "classifier_pipeline/training_onelabel.py", line 146, in <module>
    main(hparams)
  File "classifier_pipeline/training_onelabel.py", line 34, in main
    model = Classifier(hparams)
  File "/home/niallt/NLP_DPhil/NLP_Mimic_only/clinical-longformer/classifier_pipeline/classifier_one_label.py", line 200, in __init__
    self.__build_model()
  File "/home/niallt/NLP_DPhil/NLP_Mimic_only/clinical-longformer/classifier_pipeline/classifier_one_label.py", line 262, in __build_model
    max_tokens = self.hparams.max_tokens_longformer)
  File "/home/niallt/NLP_DPhil/NLP_Mimic_only/clinical-longformer/classifier_pipeline/tokenizer.py", line 17, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(pretrained_model)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_auto.py", line 220, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1425, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1572, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_roberta.py", line 171, in __init__
    **kwargs,
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_gpt2.py", line 165, in __init__
    super().__init__(bos_token=bos_token, eos_token=eos_token, unk_token=unk_token, **kwargs)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 115, in __init__
    super().__init__(**kwargs)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1311, in __init__
    super().__init__(**kwargs)
  File "/home/niallt/venvs/nlp_projects/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 658, in __init__
    "special token {} has to be either str or AddedToken but got: {}".format(key, type(value))
TypeError: special token bos_token has to be either str or AddedToken but got: <class 'dict'>

Later verions of transformers run into other issues. 

Thoughts?

**Comment by NtaylorOX** [comment]
#5 Turns out this can be resolved by upgrading transformers to current latest transformers==4.10.2. And changing the imports for importing longformer self attention as follows:

Previous code snippet for importing:

'''
from transformers.modeling_longformer import LongformerSelfAttention
'''

new code for importing

'''
from transformers.models.longformer.modeling_longformer import LongformerSelfAttention
'''
